INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("1", "AMAZONAS");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("2", "ANTIOQUIA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("3", "ARAUCA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("4", "ATLÁNTICO");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("5", "BOLÍVAR");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("6", "BOYACÁ");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("7", "CALDAS");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("8", "CAQUETÁ");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("9", "CASANARE");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("10", "CAUCA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("11", "CESAR");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("12", "CHOCÓ");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("13", "CÓRDOBA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("14", "CUNDINAMARCA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("15", "GUAINÍA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("16", "GUAVIARE");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("17", "HUILA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("18", "LA GUAJIRA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("19", "MAGDALENA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("20", "META");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("21", "NARIÑO");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("22", "NORTE DE SANTANDER");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("23", "PUTUMAYO");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("24", "QUINDÍO");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("25", "RISARALDA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("26", "SAN ANDRÉS Y ROVIDENCIA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("27", "SANTANDER");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("28", "SUCRE");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("29", "TOLIMA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("30", "VALLE DEL CAUCA");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("31", "VAUPÉS");
INSERT INTO `ciersur_departamento`( `iddepartamento`, `nombre`) VALUES("32", "VICHADA");